### ISSUE TITLE
error": "invalid_grant", "error_description": "Invalid refresh token

### ISSUE THREAD

**Issue by git-create-devben** [novatorem/novatorem#74]
After following all the guide and still not working so I decided to check the vercel function to see the log error and am seeing this so am lost 

`{"error": "invalid_grant", "error_description": "Invalid refresh token"}
---
{"error": "invalid_grant", "error_description": "Invalid refresh token"}
---
[ERROR]	2023-10-21T20:13:14.633Z	cb4210d1-4ca2-4b04-a006-eb20b003314e	Exception on /api/spotify [GET]
Traceback (most recent call last):
  File "./api/spotify.py", line 52, in refreshToken
    return response["access_token"]
KeyError: 'access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./api/spotify.py", line 174, in catch_all
    data = get(NOW_PLAYING_URL)
  File "./api/spotify.py", line 63, in get
    SPOTIFY_TOKEN = refreshToken()
  File "./api/spotify.py", line 56, in refreshToken
    raise KeyError(str(response))
KeyError: "{'error': 'invalid_grant', 'error_description': 'Invalid refresh token'}"`

**Comment by Lurku** [comment]
Did you save your ENVs after pasting it in Vercel Project Settings?
